### PR TITLE
fix: resolve cannot read property of undefined when all list items are disabled

### LINKED ISSUE #2830: [BUG]:  Dropdown Component - 'Cannot read properties of undefined' when all the options are disabled
## Detailed description

When all the options (items) provided to dropdown are disabled, there is an error popping up in the console.

```
ERROR TypeError: Cannot read properties of undefined (reading 'nativeElement')
    at DropdownList.getNextElement (carbon-components-angular-dropdown.mjs:1391:37)
    at DropdownList.updateIndex (carbon-components-angular-dropdown.mjs:1522:18)
    at DropdownList.updateList (carbon-components-angular-dropdown.mjs:1316:14)
    at set items (carbon-components-angular-dropdown.mjs:1266:18)
```

The error is happening in method `getNextElement` in [dropdown-list.component.ts](https://github.com/carbon-design-system/carbon-components-angular/blob/master/src/dropdown/list/dropdown-list.component.ts#L335-L356)

## Cause of the bug

The initial value of `this.index` is `-1`, and since all the `this.displayItems` are having disabled to true, the index value is not getting modified. So, accessing `nativeElement` from `elemList[-1]` will be undefined, the error is happening.

### PR DESCRIPTION
**Pull request by Aru-Ku**
Closes #2830 

Resolves the error, on reading nativeElement when all the list items are disabled.

For details info on the error, please refer to the issue #2830

### CODE REVIEW

File: src/dropdown/list/dropdown-list.component.ts [hunk 1]
```diff
@@ -519,7 +520,7 @@ export class DropdownList implements AbstractDropdownView, AfterViewInit, OnDest
 				}
 			} else if (event.key === "ArrowUp") {
 				if (this.hasPrevElement()) {
-					this.getPrevElement().scrollIntoView({  block: "nearest" });
+					this.getPrevElement()?.scrollIntoView({  block: "nearest" });
```
Comment (Akshat55) [inline src/dropdown/list/dropdown-list.component.ts:523]: Based on the change you made to `getNextElement()`, shouldn't optional chaining be used on line 517 instead of 523?

**Review by Akshat55 — CHANGES_REQUESTED** [review]

File: src/dropdown/list/dropdown-list.component.ts (hunk 1 above)
Comment (Aru-Ku) [reply src/dropdown/list/dropdown-list.component.ts]: Hi @Akshat55 
Yes, it went unnoticed. Fixed it now.

**Review by Akshat55 — APPROVED** [review]
